language: go

dist: trusty
sudo: required

# This moves Kubernetes specific config files.
env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - K8S_VERSION=v1.8.0
    - MINIKUBE_VERSION=v0.24.1

# Skip installation of dependencies since they are already in vendor.
install: true

go:
  - 1.8.x

git:
  depth: 1

before_script:
# Download kubectl, which is a requirement for using minikube.
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$K8S_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download minikube.
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$MINIKUBE_VERSION/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
# sudo is required when using --vm-driver=none
- sudo minikube start --vm-driver=none --kubernetes-version=$K8S_VERSION --extra-config=apiserver.Authorization.Mode=RBAC
# Fix the kubectl context, as it's often stale.
- minikube update-context
# Wait for Kubernetes to be up and running.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
- make TAG=testing image

script:
- make test
- make TESTIMAGE=kinvolk/habitat-operator:testing e2e

after_failure:
- kubectl logs -lhabitat=true --tail=100
