apiVersion: v1
kind: Secret
metadata:
  name: user-toml
type: Opaque
data:
  # Each item needs to be base64-encoded.
  # Plain text content: port = 6999
  user.toml: cG9ydCA9IDY5OTkK
---
apiVersion: habitat.sh/v1beta2
kind: Habitat
metadata:
  name: example-configured-habitat
spec:
  image: habitat/redis-hab
  count: 1
  service:
    name: redis
    topology: standalone
    group: redisdb
    # Create Secret with the initial configuration you want.
    configSecretName: user-toml
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    habitat-name: example-configured-habitat
  type: NodePort
  ports:
  # This endpoint displays the message from the secret
  - name: web
    nodePort: 30001
    # This is the custom port set in the user.toml
    port: 6999
    protocol: TCP
  # This endpoint exposes the Habitat supervisor API
  - name: http-gateway
    nodePort : 32767
    port: 9631
    protocol: TCP
