apiVersion: v1
description: A Kubernetes controller that manages Habitat services in a Kubernetes cluster.
engine: gotpl
maintainers:
  - name: Zeeshan Ali
    email: zeeshan@kinvolk.io
name: habitat-operator
sources:
  - https://github.com/habitat-sh/habitat-operator
version: 0.6.0
