apiVersion: v1
description: A Kubernetes controller that manages Habitat services in a Kubernetes cluster.
engine: gotpl
maintainers:
  - name: Krzesimir Nowak
    email: krzesimir@kinvolk.io
  - name: Iago LÃ³pez Galeiras
    email: iago@kinvolk.io
  - name: Indradhanush Gupta
    email: indra@kinvolk.io
name: habitat-operator
sources:
  - https://github.com/habitat-sh/habitat-operator
version: 0.7.1
